before:
  hooks:

builds:
  -
    id: build-linux
    main: ./cmd/aserto
    binary: aserto
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/aserto/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE.md
      - README.md
    name_template: "aserto_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: aserto-dev
    name: aserto

  draft: false
  prerelease: false
  name_template: "Aserto CLI {{.Tag}}"
