before:
  hooks:
  
builds:
  - 
    id: build-linux
    main: ./cmd/aserto
    binary: aserto
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
      - goos: darwin
    ldflags:
      - -s 
      - -w 
      - -X github.com/aserto-dev/aserto/pkg/version.ver={{.Version}} 
      - -X github.com/aserto-dev/aserto/pkg/version.commit={{.ShortCommit}} 
      - -X github.com/aserto-dev/aserto/pkg/version.date={{.Date}} 
    mod_timestamp: '{{ .CommitTimestamp }}'
    tags:
      - prod
  - 
    id: build-windows
    main: ./cmd/aserto
    binary: aserto
    goos:
      - windows
    goarch:
      - amd64
    ignore:
      - goos: linux
      - goos: darwin
    ldflags:
      - -s 
      - -w 
      - -X github.com/aserto-dev/aserto/pkg/version.ver={{.Version}} 
      - -X github.com/aserto-dev/aserto/pkg/version.commit={{.ShortCommit}} 
      - -X github.com/aserto-dev/aserto/pkg/version.date={{.Date}} 
    mod_timestamp: '{{ .CommitTimestamp }}'
    tags:
      - prod
  - 
    id: build-darwin
    main: ./cmd/aserto
    binary: aserto
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
      - goos: windows
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s 
      - -w 
      - -X github.com/aserto-dev/aserto/pkg/version.ver={{.Version}} 
      - -X github.com/aserto-dev/aserto/pkg/version.commit={{.ShortCommit}} 
      - -X github.com/aserto-dev/aserto/pkg/version.date={{.Date}} 
    mod_timestamp: '{{ .CommitTimestamp }}'
    tags:
      - prod

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE.md
      - README.md
    name_template: "aserto_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: aserto-dev
    name: aserto

  draft: false
  prerelease: false
  name_template: "Aserto CLI {{.Tag}}"
