before:
  hooks:

env:
  - REGISTRY=ghcr.io
  - ORG=aserto-dev
  - REPO=aserto

builds:
  # https://goreleaser.com/customization/build/
  - id: build
    main: ./cmd/aserto
    binary: aserto
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  # https://goreleaser.com/customization/archive/
  - format: zip
    builds:
    - build
    files:
      - LICENSE.md
      - README.md
    name_template: >-
      aserto_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}


checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'

snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: "{{ .Tag }}"

source:
  # https://goreleaser.com/customization/source/
  enabled: false

changelog:
  # https://goreleaser.com/customization/changelog/
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  # https://goreleaser.com/customization/release/
  github:
    owner: "{{ .Env.ORG }}"
    name: "{{ .Env.REPO }}"

  draft: false
  prerelease: "false"
  name_template: "{{.ProjectName}} {{.Tag}}"

blobs:
  # https://goreleaser.com/customization/blob/

brews:
  # https://goreleaser.com/customization/homebrew/
  - name: aserto

    repository:
      owner: "{{ .Env.ORG }}"
      name: homebrew-tap
      token: "{{ .Env.ASERTO_TAP }}"

    url_template: "https://github.com/aserto-dev/aserto/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    download_strategy: CurlDownloadStrategy

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://docs.aserto.com/"

    description: "Aserto CLI"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/aserto version"
    install: |
      bin.install "aserto"
