before:
  hooks:

builds:
  -
    id: build-linux
    main: ./cmd/aserto
    binary: aserto
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
      - goos: darwin
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/aserto/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
  -
    id: build-windows
    main: ./cmd/aserto
    binary: aserto
    goos:
      - windows
    goarch:
      - amd64
    ignore:
      - goos: linux
      - goos: darwin
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/aserto/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
  -
    id: build-darwin
    main: ./cmd/aserto
    binary: aserto
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
      - goos: windows
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/aserto/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/aserto/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/aserto/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE.md
      - README.md
    name_template: "aserto_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  disable: true

blobs:
  -
    provider: gs
    bucket: aserto-cli
    folder: "aserto/{{ .Version }}"
    extra_files:
      - glob: VERSION.txt
  -
    provider: gs
    bucket: aserto-cli
    folder: "aserto/latest"
    extra_files:
      - glob: VERSION.txt

brews:
  -
    name: aserto

    tap:
      owner: aserto-dev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP }}"

    url_template: "https://storage.googleapis.com/aserto-cli/aserto/{{ .Version }}/{{ .ArtifactName }}"

    download_strategy: CurlDownloadStrategy

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://docs.aserto.com/"

    description: "Aserto CLI"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/aserto version"
    install: |
      bin.install "aserto"
