name: release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  VAULT_ADDR: https://vault.eng.aserto.com/
  PRE_RELEASE: ${{ github.ref == 'refs/heads/main' && 'development' || '' }}
  GO_VERSION: "1.16"

jobs:
  release:
    runs-on: macos-10.15
    steps:
      - 
        name: Read Configuration
        uses: hashicorp/vault-action@v2.1.0
        id: vault
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/github  "SSH_PRIVATE_KEY"   | SSH_PRIVATE_KEY;
            kv/data/github  "HOMEBREW_TAP"      | HOMEBREW_TAP;
            kv/data/github  "GCP_SA_KEY"        | GCP_SA_KEY;
      - 
        name: Install Vault CLI
        uses: innovationnorway/setup-vault@v1.0.3
        with:
          version: 1.4.2
      - 
        name: Renew Vault Token
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          vault token renew
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Caching
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - 
        name: Setup Deps
        run: |
          mkdir -p $HOME/.ssh
          umask 0077 && echo -e "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
          ssh-keyscan github.com >> $HOME/.ssh/known_hosts

          git config --global url."git@github.com:".insteadOf https://github.com/
          git config --global user.email "github-bot@aserto.com"
          git config --global user.name "Aserto Bot"

          make deps
      - 
        name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - 
        name: Setup Google Cloud Credentials
        run:  gcloud info
      -
      # - 
      #   name: Build
      #   run: |
      #     make build
      # - 
      #   name: Test
      #   run: |
      #     make test
      # - 
      #   name: Lint
      #   run: |
      #     make lint
      -
        name: Release
        uses: goreleaser/goreleaser-action@v2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          version: latest
          args: release --rm-dist --config .goreleaser-prod.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP: ${{ steps.vault.outputs.HOMEBREW_TAP }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
